name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK for Gradle/Android
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Install Android SDK & required packages
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # 4️⃣ Cache Gradle to speed up builds
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5️⃣ Run JVM Unit Tests (fast, no emulator needed)
      - name: Run Unit Tests
        run: ./gradlew test

  instrumented-tests:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # ✅ Set up Android Emulator (API 30 by default)
      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel_5
          script: ./gradlew connectedCheck
